# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

# Set working directory
WORKDIR /app

# Install build dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev

# Copy requirements: use pyproject.toml and uv.lock if necessary
COPY pyproject.toml uv.lock ./
COPY README.md ./

# Install pip dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir httpx \
    && pip install --no-cache-dir "mcp[cli]>=1.4.1"

# Copy local code to the container
COPY main.py ./

# Expose MCP port if needed, but using stdio transport

# Start the MCP server
CMD ["python", "main.py"]
